---
- name: "Deloy PhpMyAdmin"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:

    - name: "Install PHP and PHP-FPM"
      when: inv_install_php | default(false)
      block:
        - name: "Include labocbz.install_php"
          tags:
            - "labocbz.install_php"
          vars:
            install_php__version: "{{ inv_install_php__version }}"
            install_php__version_is_default: "{{ inv_install_php__version_is_default }}"
            install_php__extensions: "{{ inv_install_php__extensions }}"
            install_php__install_fpm: "{{ inv_install_php__install_fpm }}"
            install_php__import_cli_conf: "{{ inv_install_php__import_cli_conf }}"
            install_php__import_apache_conf: "{{ inv_install_php__import_apache_conf }}"
            install_php__import_cgi_conf: "{{ inv_install_php__import_cgi_conf }}"
            install_php__import_fpm_conf: "{{ inv_install_php__import_fpm_conf }}"
            install_php__max_input_time: "{{ inv_install_php__max_input_time }}"
            install_php__output_buffering: "{{ inv_install_php__output_buffering }}"
            install_php__cgi_fix_pathinfo: "{{ inv_install_php__cgi_fix_pathinfo }}"
            install_php__expose_php: "{{ inv_install_php__expose_php }}"
            install_php__max_execution_time: "{{ inv_install_php__max_execution_time }}"
            install_php__memory_limit: "{{ inv_install_php__memory_limit }}"
            install_php__post_max_size: "{{ inv_install_php__post_max_size }}"
            install_php__file_uploads: "{{ inv_install_php__file_uploads }}"
            install_php__upload_max_filesize: "{{ inv_install_php__upload_max_filesize }}"
            install_php__max_file_uploads: "{{ inv_install_php__max_file_uploads }}"
            install_php__allow_url_fopen: "{{ inv_install_php__allow_url_fopen }}"
            install_php__allow_url_include: "{{ inv_install_php__allow_url_include }}"
            install_php__session_save_handler: "{{ inv_install_php__session_save_handler }}"
            install_php__session_save_path: "{{ inv_install_php__session_save_path }}"
            install_php__session_auto_start: "{{ inv_install_php__session_auto_start }}"
            install_php__session_use_strict_mode: "{{ inv_install_php__session_use_strict_mode }}"
            install_php__disable_functions: "{{ inv_install_php__disable_functions }}"
            install_php__remove_all_fpm_pools: "{{ inv_install_php__remove_all_fpm_pools }}"
            install_php__fpm_pools_path: "{{ inv_install_php__fpm_pools_path }}"
            install_php__interned_strings_buffer: "{{ inv_install_php__interned_strings_buffer }}"
            install_php__interned_strings_memory_consumption: "{{ inv_install_php__interned_strings_memory_consumption }}"
            install_php__log_level: "{{ inv_install_php__log_level }}"
          ansible.builtin.include_role:
            name: "labocbz.install_php"

        - name: "Include labocbz.add_php_fpm_confs"
          tags:
            - "labocbz.add_php_fpm_confs"
          vars:
            add_php_fpm_confs__php_version: "{{ inv_add_php_fpm_confs__php_version }}"
            add_php_fpm_confs__php_pools_path: "{{ inv_add_php_fpm_confs__php_pools_path }}"
            add_php_fpm_confs__fpm_pools: "{{ inv_add_php_fpm_confs__fpm_pools }}"
          ansible.builtin.include_role:
            name: "labocbz.add_php_fpm_confs"

        - name: "Force load proxy_fcgi"
          register: output
          changed_when: output.rc != 0
          ansible.builtin.shell: >
            a2enmod proxy_fcgi && systemctl restart apache2

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            add_logrotate_confs__files: "{{ inv_add_logrotate_confs__php_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"

    - name: "Install PhpMyAdmin"
      when: inv_install_phpmyadmin | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__phpmyadmin_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_phpmyadmin_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_phpmyadmin_cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_phpmyadmin"
          tags:
            - "labocbz.install_phpmyadmin"
          vars:
            install_phpmyadmin__blowfish: "{{ inv_install_phpmyadmin__blowfish }}"
            install_phpmyadmin__install_dir: "{{ inv_install_phpmyadmin__install_dir }}"
            install_phpmyadmin__tempdir: "{{ inv_install_phpmyadmin__tempdir }}"
            install_phpmyadmin__ssl_dir: "{{ inv_install_phpmyadmin__ssl_dir }}"
            install_phpmyadmin__php_version: "{{ inv_install_phpmyadmin__php_version }}"
            install_phpmyadmin__user: "{{ inv_install_phpmyadmin__user }}"
            install_phpmyadmin__group: "{{ inv_install_phpmyadmin__group }}"
            install_phpmyadmin__dbservers: "{{ inv_install_phpmyadmin__dbservers }}"
          ansible.builtin.include_role:
            name: "labocbz.install_phpmyadmin"

    - name: "Install Apache2"
      when: inv_install_apache | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__apache_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_add_apache_confs__configurations_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_add_apache_confs__configurations_cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_apache"
          tags:
            - "labocbz.install_apache"
          vars:
            install_apache__https_listen_port: "{{ inv_install_apache__https_listen_port }}"
            install_apache__http_listen_port: "{{ inv_install_apache__http_listen_port }}"
            install_apache__modules: "{{ inv_install_apache__modules }}"
            install_apache__enable_qos: "{{ inv_install_apache__enable_qos }}"
            install_apache__enable_security: "{{ inv_install_apache__enable_security }}"
            install_apache__security_core_version: "{{ inv_install_apache__security_core_version }}"
            install_apache__remove_all_vhosts: "{{ inv_install_apache__remove_all_vhosts }}"
            install_apache__loglevel: "{{ inv_install_apache__loglevel }}"
            install_apache__security_version: "{{ inv_install_apache__security_version }}"
            install_apache__enable_evasive: "{{ inv_install_apache__enable_evasive }}"
            install_apache__enable_pagespeed: "{{ inv_install_apache__enable_pagespeed }}"
            install_apache__enable_prefork: "{{ inv_install_apache__enable_prefork }}"
          ansible.builtin.include_role:
            name: "labocbz.install_apache"

        - name: "Import playbook custom template for Apache2"
          delegate_to: localhost
          run_once: true
          become: false
          ansible.builtin.copy:
            src: "templates/phpmyadmin.j2"
            dest: "./roles/labocbz.add_apache_confs/templates/customs/phpmyadmin.j2"
            mode: "0700"

        - name: "Include labocbz.add_apache_confs"
          tags:
            - "labocbz.add_apache_confs"
          vars:
            add_apache_confs__http_listen_port: "{{ inv_add_apache_confs__http_listen_port }}"
            add_apache_confs__https_listen_port: "{{ inv_add_apache_confs__https_listen_port }}"
            add_apache_confs__ldap_url: "{{ inv_add_apache_confs__ldap_url }}"
            add_apache_confs__ldap_port: "{{ inv_add_apache_confs__ldap_port }}"
            add_apache_confs__ldap_dc: "{{ inv_add_apache_confs__ldap_dc }}"
            add_apache_confs__auth_ldap_url: "{{ inv_add_apache_confs__auth_ldap_url }}"
            add_apache_confs__custom_ldap_base_header: "{{ inv_add_apache_confs__custom_ldap_base_header }}"
            add_apache_confs__webmaster: "{{ inv_add_apache_confs__webmaster }}"
            add_apache_confs__request_body: "{{ inv_add_apache_confs__request_body }}"
            add_apache_confs__security_body_limit: "{{ inv_add_apache_confs__security_body_limit }}"
            add_apache_confs__ssl_files_path: "{{ inv_add_apache_confs__ssl_files_path }}"
            add_apache_confs__conf_path: "{{ inv_add_apache_confs__conf_path }}"
            add_apache_confs__base_document_root: "{{ inv_add_apache_confs__base_document_root }}"
            add_apache_confs__configurations: "{{ inv_add_apache_confs__configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_apache_confs"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            add_logrotate_confs__files: "{{ inv_add_logrotate_confs__apache_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
