---
- name: "Deloy PhpMyAdmin"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  remote_user: root
  become: true
  become_method: sudo
  become_user: root

  tasks:

    - name: "Install PHP and PHP-FPM"
      when: inv_install_php | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host_system_users: "{{ inv_prepare_host_phpmyadmin_system_users}}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.install_php"
          tags:
            - "labocbz.install_php"
          vars:
            install_php_version: "{{ inv_install_php_version }}"
            install_php_version_is_default: "{{ inv_install_php_version_is_default }}"
            install_php_extensions: "{{ inv_install_php_extensions }}"
            install_php_install_fpm: "{{ inv_install_php_install_fpm }}"
            install_php_import_cli_conf: "{{ inv_install_php_import_cli_conf }}"
            install_php_import_apache_conf: "{{ inv_install_php_import_apache_conf }}"
            install_php_import_cgi_conf: "{{ inv_install_php_import_cgi_conf }}"
            install_php_import_fpm_conf: "{{ inv_install_php_import_fpm_conf }}"
            install_php_max_input_time: "{{ inv_install_php_max_input_time }}"
            install_php_output_buffering: "{{ inv_install_php_output_buffering }}"
            install_php_cgi_fix_pathinfo: "{{ inv_install_php_cgi_fix_pathinfo }}"
            install_php_expose_php: "{{ inv_install_php_expose_php }}"
            install_php_max_execution_time: "{{ inv_install_php_max_execution_time }}"
            install_php_memory_limit: "{{ inv_install_php_memory_limit }}"
            install_php_post_max_size: "{{ inv_install_php_post_max_size }}"
            install_php_file_uploads: "{{ inv_install_php_file_uploads }}"
            install_php_upload_max_filesize: "{{ inv_install_php_upload_max_filesize }}"
            install_php_max_file_uploads: "{{ inv_install_php_max_file_uploads }}"
            install_php_allow_url_fopen: "{{ inv_install_php_allow_url_fopen }}"
            install_php_allow_url_include: "{{ inv_install_php_allow_url_include }}"
            install_php_session_save_handler: "{{ inv_install_php_session_save_handler }}"
            install_php_session_save_path: "{{ inv_install_php_session_save_path }}"
            install_php_session_auto_start: "{{ inv_install_php_session_auto_start }}"
            install_php_session_use_strict_mode: "{{ inv_install_php_session_use_strict_mode }}"
            install_php_disable_functions: "{{ inv_install_php_disable_functions }}"
            install_php_remove_all_fpm_pools: "{{ inv_install_php_remove_all_fpm_pools }}"
            install_php_fpm_pools_path: "{{ inv_install_php_fpm_pools_path }}"
          ansible.builtin.include_role:
            name: "labocbz.install_php"

        - name: "Include labocbz.add_php_fpm_confs"
          tags:
            - "labocbz.add_php_fpm_confs"
          vars:
            add_php_fpm_confs_php_version: "{{ inv_add_php_fpm_confs_php_version }}"
            add_php_fpm_confs_php_pools_path: "{{ inv_add_php_fpm_confs_php_pools_path }}"
            add_php_fpm_confs_fpm_pools: "{{ inv_add_php_fpm_confs_fpm_pools }}"
          ansible.builtin.include_role:
            name: "labocbz.add_php_fpm_confs"

        - name: "Force load proxy_fcgi"
          register: output
          changed_when: output.rc != 0
          ansible.builtin.shell: >
            a2enmod proxy_fcgi && systemctl restart apache2

    - name: "Install PhpMyAdmin"
      when: inv_install_phpmyadmin | default(false)
      block:
        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_phpmyadmin_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_phpmyadmin_cert_bundles is defined
          vars:
            add_certificates_bundle_name: "{{ bundle.name }}"
            add_certificates_bundle_type: "{{ bundle.type }}"
            add_certificates_bundle_src: "{{ bundle.src }}"
            add_certificates_bundle_dest: "{{ bundle.dest }}"
            add_certificates_bundle_src_user: "{{ bundle.src_user }}"
            add_certificates_bundle_src_password: "{{ bundle.src_password }}"
            add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_phpmyadmin"
          tags:
            - "labocbz.install_phpmyadmin"
          vars:
            install_phpmyadmin_blowfish: "{{ inv_install_phpmyadmin_blowfish }}"
            install_phpmyadmin_install_dir: "{{ inv_install_phpmyadmin_install_dir }}"
            install_phpmyadmin_tempdir: "{{ inv_install_phpmyadmin_tempdir }}"
            install_phpmyadmin_ssl_dir: "{{ inv_install_phpmyadmin_ssl_dir }}"
            install_phpmyadmin_php_version: "{{ inv_install_phpmyadmin_php_version }}"
            install_phpmyadmin_user: "{{ inv_install_phpmyadmin_user }}"
            install_phpmyadmin_group: "{{ inv_install_phpmyadmin_group }}"
            install_phpmyadmin_dbservers: "{{ inv_install_phpmyadmin_dbservers }}"
          ansible.builtin.include_role:
            name: "labocbz.install_phpmyadmin"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            logrotate_configurations: "{{ inv_logrotate_configurations_php }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"

    - name: "Install Apache2"
      when: inv_install_apache | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host_system_users: "{{ inv_prepare_host_apache_system_users}}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_add_apache_confs_configurations_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_add_apache_confs_configurations_cert_bundles is defined
          vars:
            add_certificates_bundle_name: "{{ bundle.name }}"
            add_certificates_bundle_type: "{{ bundle.type }}"
            add_certificates_bundle_src: "{{ bundle.src }}"
            add_certificates_bundle_dest: "{{ bundle.dest }}"
            add_certificates_bundle_src_user: "{{ bundle.src_user }}"
            add_certificates_bundle_src_password: "{{ bundle.src_password }}"
            add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_apache"
          tags:
            - "labocbz.install_apache"
          vars:
            install_apache_https_listen_port: "{{ inv_install_apache_https_listen_port }}"
            install_apache_http_listen_port: "{{ inv_install_apache_http_listen_port }}"
            install_apache_modules: "{{ inv_install_apache_modules }}"
            install_apache_enable_qos: "{{ inv_install_apache_enable_qos }}"
            install_apache_enable_security: "{{ inv_install_apache_enable_security }}"
            install_apache_security_core_version: "{{ inv_install_apache_security_core_version }}"
            install_apache_remove_all_vhosts: "{{ inv_install_apache_remove_all_vhosts }}"
            install_apache_loglevel: "{{ inv_install_apache_loglevel }}"
            install_apache_security_version: "{{ inv_install_apache_security_version }}"
            install_apache_enable_evasive: "{{ inv_install_apache_enable_evasive }}"
            install_apache_enable_pagespeed: "{{ inv_install_apache_enable_pagespeed }}"
            install_apache_enable_prefork: "{{ inv_install_apache_enable_prefork }}"
          ansible.builtin.include_role:
            name: "labocbz.install_apache"

        - name: "Import playbook custom template for Apache2"
          delegate_to: localhost
          run_once: true
          become: false
          ansible.builtin.copy:
            src: "templates/phpmyadmin.j2"
            dest: "./roles/labocbz.add_apache_confs/templates/customs/phpmyadmin.j2"
            mode: "0700"

        - name: "Include labocbz.add_apache_confs"
          tags:
            - "labocbz.add_apache_confs"
          vars:
            add_apache_confs_http_listen_port: "{{ inv_add_apache_confs_http_listen_port }}"
            add_apache_confs_https_listen_port: "{{ inv_add_apache_confs_https_listen_port }}"
            add_apache_confs_ldap_url: "{{ inv_add_apache_confs_ldap_url }}"
            add_apache_confs_ldap_port: "{{ inv_add_apache_confs_ldap_port }}"
            add_apache_confs_ldap_dc: "{{ inv_add_apache_confs_ldap_dc }}"
            add_apache_confs_auth_ldap_url: "{{ inv_add_apache_confs_auth_ldap_url }}"
            add_apache_confs_custom_ldap_base_header: "{{ inv_add_apache_confs_custom_ldap_base_header }}"
            add_apache_confs_webmaster: "{{ inv_add_apache_confs_webmaster }}"
            add_apache_confs_request_body: "{{ inv_add_apache_confs_request_body }}"
            add_apache_confs_security_body_limit: "{{ inv_add_apache_confs_security_body_limit }}"
            add_apache_confs_ssl_files_path: "{{ inv_add_apache_confs_ssl_files_path }}"
            add_apache_confs_conf_path: "{{ inv_add_apache_confs_conf_path }}"
            add_apache_confs_base_document_root: "{{ inv_add_apache_confs_base_document_root }}"
            add_apache_confs_configurations: "{{ inv_add_apache_confs_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_apache_confs"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            logrotate_configurations: "{{ inv_logrotate_configurations_apache }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
